<?php
if(!defined('ABSPATH'))exit;
class Terttus_Trust_Bar_Widget extends \Elementor\Widget_Base{
public function get_name(){return'terttus_trust_bar';}public function get_title(){return'Terttus Trust Bar';}public function get_icon(){return'eicon-info-box';}public function get_categories(){return['terttus-widgets'];}
protected function register_controls(){$this->start_controls_section('content',['label'=>'Punkter']);$r=new \Elementor\Repeater();$r->add_control('icon',['label'=>'Ikon','type'=>\Elementor\Controls_Manager::ICONS]);$r->add_control('title',['label'=>'Titel','type'=>\Elementor\Controls_Manager::TEXT,'default'=>'Hurtig levering']);$r->add_control('text',['label'=>'Tekst','type'=>\Elementor\Controls_Manager::TEXT,'default'=>'Levering 1–3 hverdage']);$this->add_control('items',['type'=>\Elementor\Controls_Manager::REPEATER,'fields'=>$r->get_controls(),'title_field'=>'{{{ title }}}','default'=>[['title'=>'Hurtig levering','text'=>'Levering 1–3 hverdage'],['title'=>'Sikker betaling','text'=>'Tryg betaling i webshoppen'],['title'=>'14 dages fortrydelse','text'=>'Nem returnering'],['title'=>'Dansk support','text'=>'Vi hjælper dig videre']]]);$this->end_controls_section();}
protected function render(){$s=$this->get_settings_for_display();?><div class="terttus-trust-grid terttus-widget"><?php foreach($s['items'] as $item):?><div class="terttus-trust-card tt-card"><div class="terttus-trust-icon"><?php if(!empty($item['icon']['value']))\Elementor\Icons_Manager::render_icon($item['icon'],['aria-hidden'=>'true']);else echo'✓';?></div><div><strong><?php echo esc_html($item['title']);?></strong><span><?php echo esc_html($item['text']);?></span></div></div><?php endforeach;?></div><style>.terttus-trust-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.terttus-trust-card{display:flex;gap:13px;align-items:center;padding:18px}.terttus-trust-icon{display:grid;place-items:center;flex:0 0 38px;height:38px;border-radius:11px;background:rgba(20,139,147,.1);color:var(--tt-teal);font-weight:900}.terttus-trust-card i,.terttus-trust-card svg{font-size:19px;width:20px}.terttus-trust-card strong{display:block;font-size:16px;color:var(--tt-navy)}.terttus-trust-card span{display:block;margin-top:3px;color:var(--tt-muted);font-size:13px;line-height:1.35}@media(max-width:900px){.terttus-trust-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.terttus-trust-grid{grid-template-columns:1fr}}</style><?php}}


if ( isset( $widgets_manager ) && is_object( $widgets_manager ) ) { $widgets_manager->register( new Terttus_Trust_Bar_Widget() ); }
